[project]
name = "mlx8-audio-cnn"
version = "0.1.0"
description = "An example project using uv"
dependencies = [
    "torch",
    "datasets",
    "librosa",
    "soundfile",
    "tqdm",
    "matplotlib",
    "wandb"
]